//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta_Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Input
    {
        public int Id { get; set; }
        public double PatientAge { get; set; }
        public double ImageMean { get; set; }
        public double ImageMedian { get; set; }
        public double ImageStdDev { get; set; }
        public double ImageSkew { get; set; }
        public double ImageKurt { get; set; }
        public string ImagePath { get; set; }
        public double Density { get; set; }
    }
}
